### ISSUE TITLE
📚 [Docs] 이슈, pr 템플릿 생성

### ISSUE THREAD

**Issue by dkjefilsjl** [Titubeobear/TBB_FE#2]
## 💡 이슈 체크리스트

- [x] 이슈 제목: [Docs] '문서 작성 내용'
- [x] Assignees, Label을 붙여주세요.

## 📚 문서 작성해야하는 내용

- issue, pr templete 작성

## ✅ TODO

- [ ] 이슈템플릿
- [x] pr 템플릿

**Comment by kjy00** [comment]
작성 완 ~
